### ISSUE TITLE
Loading new issues in JOSM automatically

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#102]
Currently when we click skip/fix for an issue, we wait for the next issue to load and click edit again to load into JOSM. 

If to fix automatically loads the next issue into JOSM, we don't have to click edit each time.
@aaronlidman @Rub21

**Comment by aaronlidman** [comment]
Cool, I think this would be best as a setting which is turned off by default but yeah we should try it and see how it works.

**Comment by ajithranka** [comment]
We can load tasks now directly in JOSM with the to-fix plugin. Closing.
