### ISSUE TITLE
Let users download a sample csv from the UI when loading tasks

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/to-fix#103]
https://github.com/osmlab/to-fix-backend/blob/master/sample.csv is handy, but unless you wander through git, you can't see it.

Should be added to this modal https://cloud.githubusercontent.com/assets/58878/7049542/445a90e2-ddcf-11e4-9c43-dae928eed653.gif

Blocks #5

**Comment by aaronlidman** [comment]
We're moving away from CSV.
