### ISSUE TITLE
Show a message when a task is completed

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#105]
Currently when a task is complete, it just shows the world map. Having some indication that the task is complete instead of the fix/skip buttons would help avoid confusion to users who might be waiting for things to load.

Completed Task: http://osmlab.github.io/to-fix/#/task/disconnectednepal

**Comment by tristen** [comment]
Something cheap here would be to expose the completion count on all pages. i.e:

![screen shot 2015-06-06 at 11 36 25 am](https://cloud.githubusercontent.com/assets/61150/8020257/5e659654-0c40-11e5-8a01-e2dbf10a8cc9.png)

**Comment by planemad** [comment]
@tristen Is it possible to reorder tasks based on mapping activity? that would automatically move finished tasks to the bottom making it easier to find stuff to work on.

**Comment by ajithranka** [comment]
A error message is shown now when a task is complete.

<img width="468" alt="screen shot 2016-12-07 at 4 13 29 pm" src="https://cloud.githubusercontent.com/assets/11095038/20964593/2b5efcaa-bc98-11e6-9976-5504c224e195.png">
