### ISSUE TITLE
Statistics not showing correct contributors

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#106]
Today the Mapbox India data team cleared around 160 disconnected Nepal issues and completed the task. While the names show up in the activity tab, the statistics does not reflect any of our numbers, nor do the numbers add up.

http://osmlab.github.io/to-fix/?error=unconnected_major#/stats/disconnectednepal

Activity tab
![screenshot 2015-04-29 11 47 57](https://cloud.githubusercontent.com/assets/126868/7385537/990eb20c-ee65-11e4-91e1-37a8b5f71b67.png)

Statistics tab
![screenshot 2015-04-29 11 48 39](https://cloud.githubusercontent.com/assets/126868/7385542/b185fb24-ee65-11e4-8527-213c1317be06.png)

cc @aaronlidman @lxbarth

**Comment by Rub21** [comment]
close this, from the old version of to-fix
