### ISSUE TITLE
Attibution control duplicate text

### ISSUE THREAD

**Issue by geohacker** [osmlab/to-fix#110]
![screen shot 2015-05-18 at 16 24 13](https://cloud.githubusercontent.com/assets/371666/7679449/678b4078-fd7a-11e4-975c-93e7951567dd.png)

**Comment by aaronlidman** [comment]
Weird only seems to be the Mapbox satellite layer, all others behave correctly. Looking into it, think it might be upstream somewhere.

**Comment by ajithranka** [comment]
We shifted to Mapbox GL. Hopefully, this shouldn't happen again :-)
