### ISSUE TITLE
Add "not an error" button

### ISSUE THREAD

**Issue by lxbarth** [osmlab/to-fix#112]
We need a way to say "this wasn't an error".

![screen shot 2015-05-22 at 10 54 39 am](https://cloud.githubusercontent.com/assets/98233/7773208/f9688778-0070-11e5-9fdd-33fe4ca5d7bf.png)

@Rub21 - can you take this on? @aaronlidman?

cc @aaronlidman @tristen

**Comment by Rub21** [comment]
@aaronlidman , I will try to see how is working the code  in to-fix, if I have question I will let you know.

**Comment by Rub21** [comment]
@lxbarth @aaronlidman : i added the button `Not an error`  that is on this branch https://github.com/osmlab/to-fix/tree/dev

![image](https://cloud.githubusercontent.com/assets/1152236/7947305/f6efaae2-0941-11e5-9c99-cfdbb9b024ba.png)
 
and in DB is save as `"action"=>"noterror"`
![image](https://cloud.githubusercontent.com/assets/1152236/7947195/38031bdc-0941-11e5-8409-d875c8af8fa5.png)

### Next acction
Add `noterror` on stats

**Comment by lxbarth** [comment]
@rub21 - lets switch to a proper pull request.

**Comment by Rub21** [comment]
@lxbarth @aaronlidman  https://github.com/osmlab/to-fix/pull/116

**Comment by aaronlidman** [comment]
Merged! Awesome job @Rub21.
