### ISSUE TITLE
Concurrent users on same task

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#113]
We've had three cases of multiple editors working on the same task in a span of an hour resulting in editing conflicts and a messy cleanup situation.

One of the areas is here: https://www.openstreetmap.org/history#map=15/33.6492/-95.5305

@aaronlidman it looks like having a task open does not lock it? Is this something that can be fixed?

**Comment by aaronlidman** [comment]
@planemad which task was this?

The way [selections are made from the database](https://github.com/osmlab/to-fix-backend/blob/720c0dcde323cdebdb945792e02906f54fcf609c/index.js#L225-L227) it should not be possible to get the same item within a 10 minute window of another user.

**Comment by planemad** [comment]
@aaronlidman Runkeeper

**Comment by ajithranka** [comment]
This shouldn't happen any more. The new backend serves features randomly blocking them for 10 mins or so until it's reviewed.
