### ISSUE TITLE
to-fix needs to select a feature after loading the issue in JOSM.

### ISSUE THREAD

**Issue by drkludge** [osmlab/to-fix#114]
Improvement
1. select feature in JOSM when activating a task.
2. let me decide when to download more data or.
3. let me toggle an automatic download.

Background
Please look at http://keepright.ipax.at/ and http://tools.geofabrik.de/osmi/ for examples of how to implement the improvement.  I just made one change with to-fix.  Even if I turn off "Download OSM continuously" I am lost when trying to edit a task in JOSM.  I get a forest of data to look through.  I cannot tell what you think is wrong with, say, a tag spelling error, if you do not select the feature in JOSM when I click on the edit button.  The current interface creates additional problems locating the feature by automatically downloading other data.

I do not see why I can see the imagery in Firefox but not the latest version of Chrome even though I use the layer feature.  I am sure that this contributes to the problem noted above.  However, not selecting a feature in JOSM is a show stopper for me.

**Comment by Rub21** [comment]
I Think the best solution here is to uses [tofix-plugin](https://github.com/JOSM/tofix-plugin)
