### ISSUE TITLE
Encourage small changeset area and meaningful changeset names

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osmlab/to-fix#12]
Here's an example "to-fix" changeset:

http://www.openstreetmap.org/changeset/24436746

The description, "http://osmlab.github.io/to-fix/?error=keepright/nonclosedways" is not especially meaningful.  What can be done to encourage mappers to use meaningful changeset names?

Similarly, the area of that is essentially worldwide - it's not easy to see what's changed and where.

**Comment by Theodin** [comment]
I secfond that. That same problem exists with lots of other useful tools too so a wider effort is needed imho.

**Comment by ajithranka** [comment]
Each task requires a changeset comment that can be copy-pasted by a reviewer.

<img width="414" alt="screen shot 2017-07-25 at 4 00 11 pm" src="https://user-images.githubusercontent.com/11095038/28568142-5ff6a106-7152-11e7-8342-410b7f1d7d79.png">

Closing.
