### ISSUE TITLE
Same area - Different error points

### ISSUE THREAD

**Issue by shravan91** [osmlab/to-fix#120]
@aaronlidman -

@ramyaragupathy and I got the same area on to-fix Krakatoa task, but the error points were different.

We have worked on 1000 issues so far. We have encountered 3-5 issues so far issues which are repeated.

![screen shot 2015-06-12 at 2 27 45 pm](https://cloud.githubusercontent.com/assets/3190951/8126981/092d98b4-1111-11e5-826a-dc72b5712fd6.png)

@ramyaragupathy and I were working on the same area i.e. the parking which is highlighted in the screenshot. This might have resulted in a conflict.

What can we do if we have similar issues like this?

**Comment by ramyaragupathy** [comment]
Attaching a screenshot of my task which shows different error points.
![screenshot 2015-06-12 14 29 18](https://cloud.githubusercontent.com/assets/12103383/8126884/4c73b258-1110-11e5-9150-5c13c9a1faf6.png)

**Comment by planemad** [comment]
As per voice with @shravan91, the circled area was common for two different users through different tasks at the same time resulting in an edit conflict.

@aaronlidman is it normal for the hits in the same area to be split over multiple tasks like this?

**Comment by aaronlidman** [comment]
Yeah, this is part of our clustering, I don't know why it does this but can see why it's undesirable.

@morganherlocker Do you know why the same area would be clustered separately?

**Comment by morganherlocker** [comment]
The clustering algorithm has a distance threshold that determines which points should be grouped together. @MateoV do you recall what threshold value you set this to when running the clustering?

**Comment by planemad** [comment]
Task done.
