### ISSUE TITLE
To-Fix console is not working 

### ISSUE THREAD

**Issue by shravan91** [osmlab/to-fix#123]
@aaronlidman - To-Fix is not woking.

#### What is not working

- Doesn't load up any new task

![screenshot_2015-06-22_14 26 38](https://cloud.githubusercontent.com/assets/3190951/8280008/e16817a8-18f6-11e5-9510-c6bc54466ea1.png)

- The stats page is not working

![screenshot_2015-06-22_14 27 22](https://cloud.githubusercontent.com/assets/3190951/8279989/a10eeefc-18f6-11e5-988b-711c9e16899d.png)

#### Next Actions

- [ ] @aaronlidman to work on fixing the issue and update the data team

cc - @lxbarth @planemad @Rub21

**Comment by aaronlidman** [comment]
Restarted, it's working.

Eventually we'll have an alarm set up to notify me of these things.

**Comment by lxbarth** [comment]
> Eventually we'll have an alarm set up to notify me of these things.

Or @Rub21 ?
