### ISSUE TITLE
Add "Not Error" action in stats

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#124]
We have four actions. 
![image](https://cloud.githubusercontent.com/assets/1152236/8310947/bf7d2c44-1998-11e5-9bc9-ca218a5fa323.png)

on stats missing "Not Error"
![image](https://cloud.githubusercontent.com/assets/1152236/8310911/9f5b8c9e-1998-11e5-8df0-93fa9ab1c979.png)

cc. / @aaronlidman

**Comment by Rub21** [comment]
Solution: 
 https://github.com/osmlab/to-fix/commit/d8b6c9d6ffdfe6eb3aa02bc269be0b5c38a1bbbb

also in backend: 
https://github.com/osmlab/to-fix-backend/issues/39

**Comment by aaronlidman** [comment]
:+1:
