### ISSUE TITLE
Response Successful or error on upload

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#125]
@tristen Can to fix response success or error when we upload a task. right now does response anything and we don't know that was correct or not.

![image](https://cloud.githubusercontent.com/assets/1152236/8342086/5c26494e-1a8f-11e5-829f-d108bbb86a0f.png)

cc. @aaronlidman

**Comment by Rub21** [comment]
@aaronlidman  this is for confirm if a task was uploaded successful or not. 
https://github.com/osmlab/to-fix/commit/4367fafc6b9f8a399cc6ec5cc7dcfa3b90203ec1
![eeek](https://cloud.githubusercontent.com/assets/1152236/8630658/2a274e6a-272e-11e5-8506-9c2f472b0e98.gif)

**Comment by aaronlidman** [comment]
@Rub21 Rather than display a message, can you redirect to the new task instead?

**Comment by Rub21** [comment]
@aaronlidman , but for redirect to new task is necessary to implement code in `to-fix`  and add the name , source and id of task in https://github.com/osmlab/to-fix/blob/gh-pages/src/data/tasks.json, 

would be good storing [tasks.json](https://github.com/osmlab/to-fix/blob/gh-pages/src/data/tasks.json) file in DB, 

Similar : https://github.com/osmlab/to-fix-backend/issues/3

**Comment by aaronlidman** [comment]
Oh of course. That would be a good next task to hit. I'll add more details on that ticket.
