### ISSUE TITLE
Visual feedback to the user if all the task are done

### ISSUE THREAD

**Issue by baditaflorin** [osmlab/to-fix#127]
If not, i will think that you have a bug 
![capture](https://cloud.githubusercontent.com/assets/2330999/8799359/3208cb9a-2fb2-11e5-85e6-2cc0b283ca87.PNG)

**Comment by planemad** [comment]
We know have a completed tasks section.
![screenshot 2015-08-26 11 32 53](https://cloud.githubusercontent.com/assets/126868/9486543/356d5756-4be6-11e5-86cf-314c5b981556.png)
