### ISSUE TITLE
Highway intersects water - Stats not updated

### ISSUE THREAD

**Issue by ruthmaben** [osmlab/to-fix#130]
Referencing - https://github.com/mapbox/mapping/issues/103

I have been using the to-fix plugin since yesterday and it's observed that non of my edits are updated  under [this](https://github.com/mapbox/mapping/issues/103) task. Neither is there any update under activity.  I tried few edits using the web interface now and the activity sheet is getting updated. 
I had also rechecked by downloaded the [plugin](https://github.com/osmlab/josm-tofix-plugin) again this morning.

@aaronlidman could you please look into this. My edits are reflecting on yesterdays [OSM edit report](https://github.com/mapbox/data/issues/1229#issuecomment-123577891) though.

![screen shot 2015-07-22 at 6 06 03 pm](https://cloud.githubusercontent.com/assets/10308123/8825494/2bfc3d90-309d-11e5-859b-21e25ae16e08.png)

cc: @Rub21 @mapbox/team-data @planemad @lxbarth

**Comment by aaronlidman** [comment]
Hmm yes I see the issue now. I believe this is the same as https://github.com/osmlab/to-fix/issues/106

**Comment by aaronlidman** [comment]
Ok this is a little more complicated than I expected. I'll have to make the change on the backend another time.

**Comment by ruthmaben** [comment]
In that case is there a possibility this is effecting only my edits @aaronlidman .

For now, I will be working on the web interface untill the plugin issue is sorted. Did few edits using the plugin and the web interface. So far edits made in the web interface is only getting updated.

**Comment by ruthmaben** [comment]
Post discussion with @planemad, continuing edits using the plugin.

**Comment by ruthmaben** [comment]
No actions for now, closing.
