### ISSUE TITLE
[Documentation] How to create and add new to-fix tasks

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#132]
There is missing documentation on the format required for the error CSVs and how to add them to to-fix in case users are interested in updating/submitting new tasks. 

@aaronlidman and @Rub21 if you can provide me pointers to any existing documentation I can consolidate them in the wiki. What I need:
- QA sites for error sources of existing tasks
- Scripts/process used to convert data into to-fix CSV
- Sample CSVs for existing tasks
- Procedure to add CSV to to-fix

**Comment by sfkeller** [comment]
I'd like to backup @planemad's enhancement request with an addition:
1. Can you provide documentation on how to create and add new (CSV) data to an existing to-fix task?
2. Is it possible and - if yes - can you provide documentation on how to add an own new to-fix tasks?

**Comment by stevevance** [comment]
I like fixing highways, but I like fixing cycleways even more, which aren't available in to-fix. For this I use [Keep Right!](http://keepright.at/report_map.php?zoom=11&lat=41.85449&lon=-87.66141&layers=B0T&ch=0%2C170&show_ign=1&show_tmpign=1). 

<img width="242" alt="screenshot 2015-10-15 10 49 50" src="https://cloud.githubusercontent.com/assets/1330459/10519227/7ea3764c-732a-11e5-8aa3-e924c8be2f78.png">

I would like to know how to upload these as tasks!

**Comment by planemad** [comment]
@stevevance at the moment to-fix accepts issues as a csv that has a similar structure to [one of the existing tasks](https://github.com/osmlab/to-fix/wiki/Task%20sources). If you can filter the issues that would would like to focus on from the [keepright dump](http://keepright.at/interfacing.php#DUMP) and share the csv, I can create a new cycling project for you.

**Comment by planemad** [comment]
@sfkeller some basic documentation up now on https://github.com/osmlab/to-fix/wiki

The task upload itself is not public at the moment as it is quite easy for a new user to break existing tasks. Please share your csv as a new ticket and @Rub21 or I can help upload it for you.

**Comment by stevevance** [comment]
@planemad I looked into each link but I don't understand what I'd have to do. It looks like I would have to download the KeepRight dump and then extract only the points that have the error I'm looking for "highway intersects cycleway". 

Is that right?

**Comment by ajithranka** [comment]
We moved away from CSVs in favour of GeoJSONs. Closing this issues as it's no longer relevant :-)

**Comment by ajithranka** [comment]
@stevevance Let us know if we can help out with setting up a cycleways task though!

**Comment by stevevance** [comment]
@ajithranka Yes, please, I still never figured out how to make a task.

**Comment by ajithranka** [comment]
@stevevance I've updated the instructions in the [wiki]( https://github.com/osmlab/to-fix/wiki/Creating-and-updating-tasks). You should be able to upload any valid GeoJSON file now. Hope that helps!

**Comment by sfkeller** [comment]
Hi @ajithranka Many thanks for updating. So the other wiki pages "Customising CSV from varying sources" and "Output formats osmlint osmlint2csv tofix" could be marked (i.e. as remark in first section of Wiki page) as deprecated?

**Comment by ajithranka** [comment]
Thanks for pointing that out @sfkeller. I've added a note in the wiki.
