### ISSUE TITLE
Can't authorize on OSM

### ISSUE THREAD

**Issue by aawiseman** [osmlab/to-fix#133]
I clicked "Authorize on OSM" on Chrome and I keep getting 

"Application error

The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

Feel free to contact the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.

This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)"

The URL it gives me is http://www.openstreetmap.org/oauth/authorize?oauth_callback=http%3A%2F%2Fosmlab.github.io%2Fto-fix%2Foauth-complete.html&oauth_token=kTW62M5HL86SjVJrO9jXuN1Aw2yujWt7cnscQwrg

**Comment by maning** [comment]
@Rub21 can you 👀 ?

**Comment by govvin** [comment]
Same behavior using Chromium 50.0.2661.102 on Ubuntu 14.04. In Firefox, I get a blank modal window but allows me to proceed if I'm already logged-in on OSM.

**Comment by ajithranka** [comment]
This shouldn't happen now. @govvin can you let us know if you are still facing the same issue?

**Comment by govvin** [comment]
@ajithranka This is now working. Thank you.

![image](https://cloud.githubusercontent.com/assets/5821688/20965542/12978bd8-bcb1-11e6-95e4-2808e79b70a3.png)
