### ISSUE TITLE
Need clarity on Loopings

### ISSUE THREAD

**Issue by ramyaragupathy** [osmlab/to-fix#136]
Would be great if someone could clarify on what the Loopings task is intended for. Right now the problem points highlighted are essentially closed ways and there seems to be no unusual tags associated with those, but still they are indicated as erroneous ones. A few screenshots from the task.
![screenshot 2015-10-14 11 25 56](https://cloud.githubusercontent.com/assets/12103383/10475986/3c0db55e-7267-11e5-97c3-b0d148bbadd1.png)
![screenshot 2015-10-14 11 09 59](https://cloud.githubusercontent.com/assets/12103383/10475987/3c13a0cc-7267-11e5-8b68-c732f8e4d6bd.png)

cc @Rub21 @aaronlidman @planemad

**Comment by planemad** [comment]
@ramyaragupathy from http://keepright.ipax.at/

> *loopings*
Any way that contains any single node more than twice is considered an error. Any way may contain just one node twice. If more than one node is found twice it is considered an error.

Although the data seems to be throwing up a lot of false positives, or else its outdated and have been fixed. I'd say just go with the above description for now.
