### ISSUE TITLE
Set up automatically changeset comment per task

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#138]
From : https://github.com/mapbox/data/issues/1474#issuecomment-148883764

This functionality is working for to-fix plugin https://github.com/JOSM/tofix-plugin/issues/17

**Comment by aaronlidman** [comment]
This would depend on iD (https://github.com/openstreetmap/iD/issues/563) and JOSM being able to accept changeset comments in a querystring or remote control. Which isn't currently possible.

**Comment by Rub21** [comment]
@aaronlidman 
yeahh, it depend on iD :-(

However to set up a comment per default we need to add a new filed  when we are going to create a new task. right now to-fix form is [this](https://cloud.githubusercontent.com/assets/1152236/10981467/f096624e-83d5-11e5-83b3-bb37a66faad9.png) and after add a new field in form , we have to add a new filed in table [`task_details`](https://cloud.githubusercontent.com/assets/1152236/10982524/c00d9c7c-83db-11e5-980b-d77ff39b5a17.png) as well. 

what do you think? is this a good solution?

**Comment by aaronlidman** [comment]
@Rub21 - Totally agree :+1:

**Comment by bhousel** [comment]
iD has supported setting the changeset comment via querystring for a while.
see https://github.com/openstreetmap/iD/issues/2311

**Comment by aaronlidman** [comment]
Sorry I missed that.

@Rub21 - Let me know when you have this functionality added to the backend. I can add it to the front end.

**Comment by Rub21** [comment]
@aaronlidman,
 I added the functionality  on backend and frontend,  both are in branch `dev`

**Comment by Rub21** [comment]
i've added this functionality, now to-fix  web and to-fix-backend is supporting  to add changeset comment 
![image](https://cloud.githubusercontent.com/assets/1152236/14028590/52aec83c-f1cb-11e5-95ae-0ccaa03cddcd.png)
