### ISSUE TITLE
Broken stats

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#140]
the to-fix stats is broken, 
![image](https://cloud.githubusercontent.com/assets/1152236/11648996/d1bfbd14-9d9f-11e5-89f3-5fced8fb1d20.png),

I think the d3 library is not working, any idea?

cc. @aaronlidman @tristen

**Comment by aaronlidman** [comment]
![screen shot 2015-12-08 at 10 05 07 am](https://cloud.githubusercontent.com/assets/58878/11658887/48ba0a08-9d93-11e5-8795-58a99b9c3bbc.png)

Included d3 and rebuilt: https://github.com/osmlab/to-fix/commit/0cf90ffb235563d671456402c2d368f37631c482

Not sure why it worked before without d3, weird.
