### ISSUE TITLE
Can't add new task - 401 form mapbox/csv

### ISSUE THREAD

**Issue by rustyb** [osmlab/to-fix#141]
Howdy Folks - I am trying to set up a new task for #MapLesotho to fix up roads marked as tracked in residential areas.

However I am running into a issue setting up a new task, I receive a 401 not authorised from [to-fix-backend.mapbox.com/csv](https://to-fix-backend.mapbox.com/csv).

```
{statusCode: 401, error: "Unauthorized", message: "invalid password"}
error: "Unauthorized"
message: "invalid password"
statusCode: 401
```
Not sure why the password is being marked as invalid since it is a new task. Are there any specific format requirements for the password?

Sample of the csv i am trying to upload in the keepright style is below:

```
"object_type","object_id","st_astext"
"way",367893266,"POINT(27.9332452281383 -28.9368578805378)"
"way",367892758,"POINT(27.9362712429366 -28.9368936224659)"
"way",367865107,"POINT(27.9368141579701 -28.9357008090967)"
```

Would really appreciate any help with the above!

**Comment by planemad** [comment]
@rustyb thanks for reporting, for now all uploads do require a password to upload to the backend. But there seems to be some other issues as well. I'm getting 

```
{"statusCode":400,"error":"Bad Request","message":"Error: EACCES, open '/mnt/uploads/unconnected.csv'"}
```

@Rub21 any idea what could be wrong?

**Comment by Rub21** [comment]
@rustyb,
> {"statusCode":400,"error":"Bad Request","message":"Error: EACCES, open '/mnt/uploads/unconnected.csv'"}

I guess it is a password problem or maybe CSV problem. can you sent me your csv file, which want to upload in to-fix.

**Comment by rustyb** [comment]
Hi @Rub21 thanks a mill for getting back to me.

I have placed the csv file in this gist - https://gist.github.com/rustyb/1bc26ffc68c31a304c71

Task Name: #MapLesotho - Track Assessment
Source: keepright
Description: Reviewing of highway: track in residential areas to see if should be changed to highway: residential.

Hopefully it's not something wrong with the file!

**Comment by Rub21** [comment]
@rustyb  , 
the problem was double quotes in you file, I upload you task in to-fix now is available on web an plugin. 
![image](https://cloud.githubusercontent.com/assets/1152236/13083367/afd3d746-d4a2-11e5-9281-d1f0c264dffa.png)
![image](https://cloud.githubusercontent.com/assets/1152236/13083382/c281af76-d4a2-11e5-93b0-c303203bf919.png)

Any problem , let me know :)

**Comment by rustyb** [comment]
@Rub21 Thanks a mill for sorting that! So in future I will make sure to strip out the double quotes.

Task looks great! Stripping the double quotes would allow me to add other tasks right?

Cheers! :D

**Comment by Rub21** [comment]
@rustyb 
>  Stripping the double quotes would allow me to add other tasks right?

yes!
