### ISSUE TITLE
add support for invalid relations task

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#146]
It should display the  broken relation 
http://osmlab.github.io/to-fix/#/task/invalidrelations
![image](https://cloud.githubusercontent.com/assets/1152236/15372079/54f504d0-1d04-11e6-8a36-4c903855657c.png)

cc. @aaronlidman @rclark

**Comment by rclark** [comment]
Because the relation's geometry is invalid, I can't give you GeoJSON for the relation itself. Furthermore, that geojson might be enormous. 

In another situation I tried providing a BBOX that includes all the points in the relation. Would that be sufficient?

**Comment by Rub21** [comment]
@rclark this is not a detection problem, the csv file is fine, but I not sure if we can add   broken relation using  leaflet-omnivore.

**Comment by rclark** [comment]
It is also possible to provide all the way IDs that make up the relation if that would be helpful.

**Comment by Rub21** [comment]
@rclark   that would be much better,  the Id of way between the both points  or the way where the relation has the problem. 

![54f504d0-1d04-11e6-8a36-4c903855657c](https://cloud.githubusercontent.com/assets/1152236/15373421/2ab41cc2-1d0b-11e6-81b9-fa5f7f92da66.png)

**Comment by rclark** [comment]
I can provide ids for all the ways in the relation in every case. I can only provide the way where the relation has the problem in some cases. Sometimes that might be more than one way -- example is two ways that intersect each other and are both part of the relation.

I will be able to have this for you tomorrow.

**Comment by Rub21** [comment]
Nice!
> Sometimes that might be more than one way 

i think on this case just we  need the id from one of them, it is just to  display  in to-fix web and make a selection after downloaded in to-fix plugin. 

the main thing is the Point and MultiPoint  , using the the point the apps can display where is exactly  the error, the id of way help to check which of the way has the error, but it is not really a   big deal, because if we know where is the error we can know the way related on the problem.

**Comment by ajithranka** [comment]
Closing for now.

@Rub21 please re-open if we look at relations later.
