### ISSUE TITLE
Whitelist countries with highly active OSM communities

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#147]
As per OSM guidelines of **Local knowledge first**, to-fix should not encourage mass edits remotely in areas with a highly active local mapping community with field knowledge. 

This has repeatedly caused issues especially in UK, where the satellite imagery may be old or is not clear enough to make a remote edit. See https://github.com/mapbox/mapping/issues/186 . 

@Rub21 how can we immediately drop tasks in certain areas of the map:
- UK
- Germany
- Switzerland
- France
- Netherlands
- Belgium

cc @maning @mikelmaron @geohacker

**Comment by Rub21** [comment]
Done here! just we need to remove from this list https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt , 
> UK
Germany
Switzerland
France
Netherlands
Belgium  


Today detection won't include  the above countries.

**Comment by planemad** [comment]
👍

**Comment by pnorman** [comment]
The root cause is people using to-fix to edit stuff they don't understand, and I'm concerned that now cases of that will just go unobserved

**Comment by RicoElectrico** [comment]
How about giving (mainly non-Mapbox) users ability to filter to-fix issues by country/arbitrary area? This is much requested and I think would help you get manpower to finish tasks even quicker. Mappers obviously care more for their local area. 
I know that because the data team fixes things worldwide and this is why this feature isn't a priority for Mapbox. But the reasons above in my opinion justify implementing it in a non-sometime.

I also wonder how the list was compiled. It deviates a little from OSMStats.

**Comment by planemad** [comment]
@pnorman this is a larger OSM issue where there are no local mapping communities to check edits. Not sure how to-fix would be able to solve that unless one displays a large notice each time warning users to only edit what they do know. Please share any ideas you may have, we could try it out.

**Comment by planemad** [comment]
@RicoElectrico geographic filter is certainly a useful feature and implementing it will require re-architecting the whole tool. The next iteration will include this. The country list was pretty rough, if any particular community would not like edits via to-fix, we can expand it.

**Comment by pnorman** [comment]
> @pnorman this is a larger OSM issue where there are no local mapping communities to check edits. Not sure how to-fix would be able to solve that unless one displays a large notice each time warning users to only edit what they do know. Please share any ideas you may have, we could try it out

Make sure that users don't edit without understanding what they're changing.
