### ISSUE TITLE
Check if to-fix is setting the changeset comment correctly

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#148]
A recent report https://github.com/mapbox/mapping/issues/186#issue-155992209 indicates that changeset comments on "islands minor highways" to-fix task was incorrect. What could be the reason behind this?

cc @Rub21

**Comment by Rub21** [comment]
@samely puedes comprobar esto?

**Comment by samely** [comment]
I'm sure this works.
![image](https://cloud.githubusercontent.com/assets/10425629/15615331/4a2610c0-2403-11e6-851e-0cf521e1f9d6.png)
*Changeset comment*
![image](https://cloud.githubusercontent.com/assets/10425629/15615348/5e61d5e2-2403-11e6-90bf-a3f3acc62a80.png)
*Comment in OSM Changeset*

SomeoneEsle is talking about Pavel's changesets. He was not updating his comment when starting to work on another project or task that don't get automatically the comment.

**Comment by govvin** [comment]
I'm using JOSM v. 10168 and it doesn't set the comments to the task default set. I have to manually copy the recommended comment string.

**Comment by Rub21** [comment]
if you are clicking  on `upload` button  on menu bar 
![image](https://cloud.githubusercontent.com/assets/1152236/17625874/5c606a02-6070-11e6-8407-3cfd5f819eb5.png)
it won't call the comment , you should click in the `fixed` button.
![image](https://cloud.githubusercontent.com/assets/1152236/17625896/81daf950-6070-11e6-8a89-cc00ea0df57b.png)
