### ISSUE TITLE
Whitelist China

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#149]
Mapping is technically illegal in China http://wiki.openstreetmap.org/wiki/WikiProject_China#Legality

Lets not get mappers to fix data in areas where there is no provision for a local community to exist legally.

cc @Rub21

**Comment by aaronlidman** [comment]
There is no straightforward way to whitelist. It would be better to filter out the source data before uploading. For most cases that comes from [osmlint](https://github.com/osmlab/osmlint).

**Comment by Rub21** [comment]
@planemad @aaronlidman , we are not  detecting issues from China, [this list](https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt) mention the countries where we are focusing in to-fix.
