### ISSUE TITLE
Refactoring the to-fix front-end

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#152]
We building a new version of to-fix according the below tickets, an experience to handle the tasks and a tools  that community can use for their projects
- [Define a standardized format for map issues](https://github.com/osmlab/to-fix/issues/150)
- [Switch csv to geojson](https://github.com/osmlab/to-fix-backend/issues/49)
- [[Documentation] How to create and add new to-fix tasks](https://github.com/osmlab/to-fix/issues/132)
- https://github.com/osmlab/to-fix/issues

We are also changing the ways to handle the task. We are going to use projects, tasks and items, these will help to community to create their own projects and tasks without any restriction.

So far  we have some progress on back-end, https://github.com/osmlab/to-fix-backend/pull/50. however we need to work in parallel the back and front site to make more consistent functionalities.

Would be great guys if you can jump on this refactoring.

cc. @rodowi @aaronlidman  @batpad @ajithranka @planemad @maning

**Comment by rodowi** [comment]
_Note: I've updated @Rub21's comment to add the issue title to the links above_

Just jumping in to the project.

My first impression is that a front-end refactor is not the next step. A lot of things are happening in osmlab/to-fix-backend#50 and the front-end needs to catch up.

I'd suggest tackling the tasks in the following order:
1. Define the GeoJSON format
2. Switch both frontend and backend to this new format (skipping the Projects logic)
3. Define the UI for Projects
4. Add the Projects feature on front/back staging instances
5. Update production
6. Document how to create projects and tasks
7. Refactor the code for the new features

General refactor will happen as the projects moves forward.

**Comment by rodowi** [comment]
per voice w @Rub21 we agree on the following next steps

- Authorized users can create projects
- Authorized users can group tasks by project
- Switch from password-based auth to OSM OAuth
- Support GeoJSON for tasks #150
- Document how to create projects and upload tasks #132

I'd suggest not removing any existing functionality yet (like CSV support) until we test this new workflow for a while.

**Comment by aaronlidman** [comment]
Sounds great.

>Switch from password-based auth to OSM OAuth

What's the reason for the change here? to-fix already authenticated through oauth with [osmauth](https://github.com/osmlab/osm-auth) which is also used by iD. Is there a reason for moving away from it?

**Comment by Rub21** [comment]
@aaronlidman 
> What's the reason for the change here? to-fix already authenticated through oauth with osmauth which is 
yes! 

but we need use authentication to able create projects and tasks,  currently to create a a task we are using a password, which is not working fine.

**Comment by rodowi** [comment]
yea, is for project and task creation (I've updated the list above to make it clear)

**Comment by aaronlidman** [comment]
👍 Perfect.

**Comment by ajithranka** [comment]
Done. Projects work is tracked in separate tickets.
