### ISSUE TITLE
Authorization on OSM not possible

### ISSUE THREAD

**Issue by Nakaner** [osmlab/to-fix#154]
I cannot authorize with OSM. If I click on "Authorize on OSM", a new small browser windows opens but there is only `about:blank` loaded.

This happens both with Mozilla Firefox for Ubuntu 48.0 (Ubuntu 14.04 64 Bit) and Chromium 51.0.2704.79 (same operating system).

**Comment by rodowi** [comment]
Thanks for reporting

Closing this ticket as it is duplicated in #133
