### ISSUE TITLE
Use GL

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix#155]
@ajithranka - Can you update this project to use mapbox-gl-js instead of mapbox.js?

This will require some workarounds for using the `leaflet-omnivore` and `leaflet-osm` plugins, but that code is public and should be adaptable.

**Comment by ajithranka** [comment]
As a first step, I want to take a look for a way to wrap Mapbox GL JS as React components. This should help us compose a set of sources, layers and event handlers together. Autochethan currently uses [`maps-react`](https://github.com/kepta/maps-react), which was quickly developed  and lack some of the features we need.

**Comment by aaronlidman** [comment]
@ajithranka - Did you pick a library or build your own?

**Comment by ajithranka** [comment]
@aaronlidman After exploring a bit with [react-mapbox-gl](https://github.com/mapbox/react-mapbox-gl), I think it's best to start with bare-bones React + Mapbox GL instead and not introduce a abstraction on top of it. It's easy to get as far as abstracting sources and layers, but it gets difficult when trying to get event handlers and controls to work well with these components. 

I'm going to put `react-mapbox-gl` on hold for now, untill I figure out a cleaner solution. For `to-fix` though, I'd suggest not introducing a library until we need one.

**Comment by ajithranka** [comment]
Moved to GL after [PR #160](https://github.com/osmlab/to-fix/pull/160).
