### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by tmcw** [osmlab/to-fix#16]

**Comment by geohacker** [comment]
The only shortcuts that seem to work at the moment are - 
1. 's' - Skip
2. 'e' - Edit

We want - 
1. 'f' - Fixed

@planemad @shravan91

**Comment by tristen** [comment]
:eyes: will make sure this is adapted into the [react branch](https://github.com/osmlab/to-fix/tree/react) I'm working in.
