### ISSUE TITLE
Replace "next task" button in iD with edit actions

### ISSUE THREAD

**Issue by ajithranka** [osmlab/to-fix#165]
![screen shot 2016-11-24 at 2 28 20 pm](https://cloud.githubusercontent.com/assets/11095038/20592328/d85b9fa8-b252-11e6-8065-a121bafa98d6.png)

After opening a item in iD, we should keep track of whether the item is marked as fixed, skipped or not a error. Right now, we are tracking only that the task was viewed in iD and not what action was taken.

cc: @aaronlidman @Rub21

**Comment by rasagy** [comment]
This should also try to take in account @talllguy’s comment on handling editing in iD and [switching to the next task without saving](https://github.com/osmlab/to-fix/issues/119).

**Comment by ajithranka** [comment]
When switching to the next task, an alert is thrown if there are unsaved changes in iD. We may not be able to rely on this completely however. Because we are embedding iD, there might not be a straightforward way to check for unsaved changes.

<img width="1069" alt="screen shot 2017-02-08 at 4 57 38 pm" src="https://cloud.githubusercontent.com/assets/11095038/22735522/0815d4b2-ee20-11e6-9eea-7ff85aa3ff65.png">

@bhousel Any way we can check for this in iD?

**Comment by bhousel** [comment]
I think it's possible to do what you want here.. If I understand correctly, you want to change "Next Task" from opening a new iD tab with the next task to instead controlling the existing iD application.

To do that you'll need to
- recenter the iD map
- enter Select mode with thing(s) selected

Is that right?

**Comment by ajithranka** [comment]
@bhousel The issue is a user might make changes to the map but forgets to save it before moving to the next task. Is there a way we can detect if there are unsaved changes in iD? We are embedding iD in an iframe, so we don't have any access to iD's environment.

**Comment by bhousel** [comment]
Can to-fix just post messages to the iframe to control iD?  http://stackoverflow.com/a/9154267/7620

**Comment by ajithranka** [comment]
Thanks @bhousel, that looks interesting. I'm going to give it a try on a separate PR.
