### ISSUE TITLE
LineString display as a Polygon

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#174]
I just added a tiger delta task in to-fix, but on the web, it display as polygon
![image](https://cloud.githubusercontent.com/assets/1152236/21596160/596b2426-d105-11e6-9e1a-262dcb301771.png)

cc. @ajithranka

**Comment by ajithranka** [comment]
@Rub21 This should be fixed now. Let me know if you still see fills.

**Comment by Rub21** [comment]
done!!
