### ISSUE TITLE
Master ticket: Version 1.0 release

### ISSUE THREAD

**Issue by ajithranka** [osmlab/to-fix#176]
Tasks to hit out before the next release. Timeline: end of January.

- UI [milestone](https://github.com/osmlab/to-fix/milestone/1).
- Server-side authentication and user permissions. -- #159 
- Design improvements to the UI and map style, cc: @rasagy.
- Documentation refresh.

Please let me know if there's anything else we should add.

cc: @aaronlidman @Rub21 @geohacker @batpad @rasagy

**Comment by ajithranka** [comment]
Update:

- Server-side auth is done. Next: [add a admin page to manage user permissions](https://github.com/osmlab/to-fix/issues/180).
- Stats-related fixes. PR #186.

**Comment by rasagy** [comment]
Small set of todo items from a short walkthrough of the To-fix UI:

Type | Description | Status
---- | ----------- | ------
Styling | Descriptions: Wrap the truncating comments & descriptions |  
Styling | Descriptions: Copy comments button |  
Styling | Descriptions: Make `v` button more clickable |  
Styling | Descriptions: Make panel responsive |  
Styling | Descriptions: Disable user select/highlight on rest of text |  
Styling | Preview button should change pointer on hover |  
Styling | Map design: Improve feature layer colors |  
Styling | Top tabs & Login button: spacing & float issues |  
Styling | Tooltip for task names that are truncated |  
Styling | Tooltip for location in Preview section |  
Styling | Profile popup: styling + better hover states |  
Styling | Edit & action bar breaks on resizing |  
Styling | Statistics table style |  
Copy | Activity: Change text to Edit_ed_, Skip_ped_, Fix_ed_, Not an error |  
Copy | Activity: Update message for all activity loaded |  
Copy | Relook at all error messages |  
Bug | GL JS update breaks map at small widths (can’t fitbounds() ) |  
Feature Request | UI: Layer selector (Mapbox Satellite, Streets) |  
Feature Request | Edit icons on tasks that the user _can_ edit, disable which you can’t |  
Feature Request | Default photo for user + take care of portrait photos |  
Feature Request | Errors when 503 (or any server side error happens) |  
Feature Request | Can we cancel loading and align loading indicator to center of the _map_ |  

@ajithranka & I will tag team to hit as many of these as possible, will open ticket for those issues that need more discussions.

cc @geohacker @batpad @planemad

**Comment by ajithranka** [comment]
Closing. Let's revisit individual feature requests separately.
