### ISSUE TITLE
Design an admin interface for adding tasks and permissions

### ISSUE THREAD

**Issue by rasagy** [osmlab/to-fix#180]
Starting this ticket to focus on the admin interface. As of now it is:

![image](https://cloud.githubusercontent.com/assets/1117531/21838401/ced21fb4-d7f7-11e6-8d30-f47881217131.png)

Once we move the details of the task #63 to the main view, we can dedicate this section for adding new projects and editing details of existing projects from #158, and specific users could see another tab for user permissions from #159.

cc @ajithranka

**Comment by ajithranka** [comment]
Done.
