### ISSUE TITLE
unable to login, using chromium on linux

### ISSUE THREAD

**Issue by govvin** [osmlab/to-fix#208]
When trying to view the [website](https://osmlab.github.io/to-fix/#/) using Chromium, on Linux, I only see the throbber.

![image](https://cloud.githubusercontent.com/assets/5821688/26038365/887d1354-3939-11e7-81eb-49fe4e7b387c.png)

This is on Chromium version 58.0.3029.96 Built on Ubuntu , running on Ubuntu 16.04 (64-bit).

On this same machine, using Firefox, the website works fine.

**Comment by ajithranka** [comment]
Hey @govvin, are you seeing any errors in the browser console?

**Comment by govvin** [comment]
@ajithranka  Please see attached.

By the way, now I couldn't log-in with Firefox and Chromium

[osmlab.github.io-1495532192568.log.txt](https://github.com/osmlab/to-fix/files/1021652/osmlab.github.io-1495532192568.log.txt)

**Comment by ajithranka** [comment]
This should be fixed after [to-fix-backed/issues/96](https://github.com/osmlab/to-fix-backend/issues/96).

@govvin Let me know if you are able to login now.

**Comment by govvin** [comment]
Yes, that's confirmed.  I noticed that earlier today. Thank you!

However, I couldn't get iD to launch for editing.
