### ISSUE TITLE
I couldn't edit using the iD editor on FF 53.02. 

### ISSUE THREAD

**Issue by govvin** [osmlab/to-fix#209]
I couldn't edit using the iD editor on FF 53.02. 

Also, the browser control reports the iD link is to "http://preview.ideditor.com/"

![image](https://cloud.githubusercontent.com/assets/5821688/26441581/ac96ad04-4163-11e7-8c02-df3187d65a57.png)

**Comment by ajithranka** [comment]
Hi @govvin, this is an issue with iD being served over `http`. One workaround for now is to enable loading unsafe scripts on your browser. 

![load unsafe scripts](https://cloud.githubusercontent.com/assets/11095038/26448853/00911df0-416d-11e7-9021-f5745a51684d.png)

cc: @bhousel

**Comment by govvin** [comment]
In Firefox, even after disabling protection (which I suppose is the equivalent for this) didn't work for me.

**Comment by govvin** [comment]
@ajithranka 
I just tried this on Chrome (Linux), and got this error from the browser console after allowing it load unsafe scripts:
![image](https://cloud.githubusercontent.com/assets/5821688/26478103/86222ba0-41fc-11e7-8938-49f6d4daa56d.png)

**Comment by ajithranka** [comment]
This should be fixed once iD moves to https.

**Comment by bhousel** [comment]
cc @iandees and @miccolis
It would be really great to get https working on the preview.ideditor.com domain.
