### ISSUE TITLE
Can not open an issue in iD

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#211]
![image](https://user-images.githubusercontent.com/1152236/27709107-c38915ce-5ccf-11e7-99d5-9e5e66a4336c.png)

cc. @ajithranka

**Comment by boeleman** [comment]
I cannot open an issue in ID in chrome either and get the error "This page is trying to load scripts from unauthenticated sources"

**Comment by ajithranka** [comment]
Related to #209.

iD is currently served over `http` and gets blocked by the browser.
We don't really have a good fix for this right now.

As a workaround, try enabling loading unsafe scripts on your browser. 

![load unsafe scripts](https://cloud.githubusercontent.com/assets/11095038/26448853/00911df0-416d-11e7-9021-f5745a51684d.png)

cc: @bhousel

**Comment by ajithranka** [comment]
Not actionable right now. Closing.
