### ISSUE TITLE
admin option missing - doesn't support creating new tasks?

### ISSUE THREAD

**Issue by govvin** [osmlab/to-fix#220]
* **I'm submitting a ... **

  - [ ] bug report
  - [ ] feature request
  - [x ] support / question

## *Brief Description*
I'm looking for a micro-tasking manager that can handle adding POIs and tags (supplied by  data owners) for adding into OSM manually. Is such behaviour actually supported by to-fix?

## What is the motivation / use case for this feature?
Adding a batch of POIs manually, with validation

## What  is the current behaviour, (attach relevant screenshots) ?
There used to be an admin option available, but I couldn't see them now.

## What  is the expected behaviour ?
Missing admin option.

**Comment by ajithranka** [comment]
Hey @govvin, I've given you admin access to your account (OSM username: GOwin).

Here are the steps to create a new task:

1. Click your user profile and select "Manage tasks".

<img width="147" alt="screen shot 2017-08-08 at 2 52 07 pm" src="https://user-images.githubusercontent.com/11095038/29065618-472dfff4-7c4a-11e7-9cb4-94c17cfab22d.png">

2. Select "Create a new task" on the sidebar.

<img width="210" alt="screen shot 2017-08-08 at 3 00 21 pm" src="https://user-images.githubusercontent.com/11095038/29065637-5f01b346-7c4a-11e7-81d7-765fbbefe9fd.png">

3. Fill in the new task form and upload a GeoJSON. Each feature in the GeoJSON will need a unique `id` property.

<img width="444" alt="screen shot 2017-08-08 at 3 01 01 pm" src="https://user-images.githubusercontent.com/11095038/29065687-80948b1e-7c4a-11e7-9431-baf561bdf151.png">

Let me know if this works for you.

**Comment by govvin** [comment]
Thank you for the quick response @ajithranka .

There was some initial hiccup with the initial test data I used earlier, and I suspected it's the negative `id` values I have in the geojson - but that's been resolved. I'll be uploading the working data we'll be using soon.

Again, thank you. I appreciate your quick action.
