### ISSUE TITLE
[PSA] Deprecating to-fix instance

### ISSUE THREAD

**Issue by maning** [osmlab/to-fix#226]
For the last couple of months, our team at Mapbox ran into several performance issues and closing the Elastic Search DB made much more sense.  The Mapbox team is heads-down on building a new infrastructure for a more robust backend for this tool. We are very excited to share this with the rest of the community very soon. 

This shutdown affects the following services effective immediately:

- Mapbox hosted to-fix backend
- OSMLab hosted to-fix frontend - https://osmlab.github.io/to-fix/#/
- to-fix JOSM plugin using the Mapbox hosted backend - https://github.com/JOSM/tofix

All code is open source so anyone can run their own instance if they wish to do so:

- Frontend - https://github.com/osmlab/to-fix
- Backend - https://github.com/osmlab/to-fix-backend/

We thank the OSM community for using this tool in their regular mapping.

**Comment by ahmadazimi** [comment]
I think this is more helpful if you put this announcement on the README.md in homepage of this project!
