### ISSUE TITLE
Wrong mixedlayer on covered=colonnade + tunnel=building_passage

### ISSUE THREAD

**Issue by OverQuantum** [osmlab/to-fix#53]
This is wrong "fix": http://www.openstreetmap.org/changeset/27025584
Pathways are on the same layer (photo proof: http://mosday.ru/photos/61_184.jpg ), so they should not be disconnected.
Such cases should not be fixed automatically.

**Comment by Rub21** [comment]
This changeset was reverted:
![image](https://cloud.githubusercontent.com/assets/1152236/10085331/3652bcb6-62ce-11e5-9f26-cd20098a3617.png)

Close  this ticket here!

**Comment by planemad** [comment]
@OverQuantum thanks for reporting. The data comes from http://keepright.at and we have no way of filtering based on tags.
