### ISSUE TITLE
Add sentry error tracking

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix#62]

**Comment by aaronlidman** [comment]
Added in e696c4318b967d140b81f778a5db3612736da271

**Comment by kepta** [comment]
I think we should add sentry again to `to-fix`. It would be great to addition to the development cycle. @ajithranka what do you say?

**Comment by ajithranka** [comment]
Sounds good!

Here's my [commit]((https://github.com/osmlab/to-fix/commit/0e8c2800ef7568bee373662b024348bddee3e089)) that removed sentry.
