### ISSUE TITLE
About page/modal

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix#71]
Just need a simple "About" page to display some general information about to-fix, link to this repo, and list stuff that makes to-fix possible.

I think this would best fit at the bottom of the sidebar, even if it's slightly hidden.

![screen shot 2015-03-15 at 4 21 14 pm](https://cloud.githubusercontent.com/assets/58878/6657911/680a92ce-cb2f-11e4-9bc0-ebd6740b250e.png)

**Comment by tristen** [comment]
@aaronlidman @geohacker  Want to pull together some copy for this? I can hook it up into the system.

**Comment by tristen** [comment]
We should also incorporate this into it: https://github.com/osmlab/to-fix/issues/68
