### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix#74]
Splitting out of [uploads](https://github.com/osmlab/to-fix/pull/72), as that's all ready to go.

- [ ] Stats interface
- [x] An activity feed

#### Stats
- Show a progress bar + number of how many items done total in a task
- Show number of tasks done today
- Show average number of time / task
- All graphs and graph configurations linkable for sharing
- Nice to have: clean graph view w/ live updates for showing progress on monitor in office
- Will require considerable backend work

#### Activity feed
- Very basic, like github dashboard
- No need to add links or very many details etc for now

This coincides with some back end work: https://github.com/osmlab/to-fix-backend/issues/1

**Comment by tristen** [comment]
Just talked to @aaronlidman about this. It makes sense for activity and a brush graph timeline to be combined together and served from a single `activity/` path.
