### ISSUE TITLE
Errors in the new To-Fix

### ISSUE THREAD

**Issue by shravan91** [osmlab/to-fix#77]
Posting screenshots of errors I came across, which loads up on the console: 

![screen shot 2015-03-18 at 5 17 06 pm](https://cloud.githubusercontent.com/assets/3190951/6708965/33c12302-cd9b-11e4-9f6d-1c7bf5b33956.png)

*The loading gif keeps on rotating and then the page needs to be refreshed*

![screen shot 2015-03-18 at 6 15 59 pm](https://cloud.githubusercontent.com/assets/3190951/6708969/3674da9e-cd9b-11e4-853b-72b1a496b2a3.png)

*This is what the console shows up when the to-fix page is loading up every time with a new issue*

cc- @aaronlidman @geohacker

**Comment by aaronlidman** [comment]
@shravan91 I fixed this. That second error looks like some chrome extension is interfering though, let me know if that keeps happening.
