### ISSUE TITLE
To- fix issues

### ISSUE THREAD

**Issue by ruthmaben** [osmlab/to-fix#78]
@aaronlidman   - Sharing observations of few concerns we are facing  while working on to-fix - 

- We are coming across a lot of areas which are already fixed.
- Few instances are, once we edit a area and click on fixed,the next image skips for a minimum of 4-5    times till we get the next area to edit.
- Once we click on fixed, it takes a lot of time to upload the imagery for us  to get the next area to edit.

![screen shot 2015-03-18 at 6 37 35 pm](https://cloud.githubusercontent.com/assets/10308123/6709281/0aa98bd2-cd9e-11e4-9fdb-3a30f4f5ba0b.png)

- Previously we used to get the node highlighted in Red which indicated the node to be fixed,as of now we are not getting that display on most of the imagery and we find it difficlut to find the exact node to be fixed . 

Below screen shot highlights the area to be fixed on to-fix, but we find no indication on JOSM ( node not highlighted)

![screen shot 2015-03-18 at 6 33 19 pm](https://cloud.githubusercontent.com/assets/10308123/6709227/59374dc6-cd9d-11e4-8a81-3aa3e0f57b74.png)

cc: @planemad @srividyacb @shravan91 @lxbarth @geohacker

**Comment by aaronlidman** [comment]
Thanks @ruthmaben, I know what this is. Will get on it today.

**Comment by aaronlidman** [comment]
I fixed the areas that were already fixed, that was a mistake on my part. The skipping was related to that as well.

I'm not sure what 3 could be.

The highlighting was a nice feature that got dropped by accident, it will be back soon.

**Comment by ruthmaben** [comment]
Thanks @aaronlidman .
