### ISSUE TITLE
Unreliable unconnected major data stream

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#84]
We rely exclusively on the [OSM inspector](http://tools.geofabrik.de/osmi/) data stream from geofabrik for unconnected major errors. While this data is supposed to be updated daily, a comparison between the past two days data revealed a reduction in the global error count by 26. The Bangalore data team fixes 200+ issues a day in total and it seems unlikely that so many new errors were newly created.

Also in the [unconnected major error map](http://geohacker.in/unconnected-tiger/), we find some errors have already been fixed many days ago, but is still part of the data, so there is clearly issues with relying exclusively on OSMI for the error stream.

The number of fixed issues being shown by to-fix is increasing and this causes significant time to be lost in investigating the problem and moving to the next one.

In the long run we definitely need to generate our own error stream that we can control and rely on.

cc @aaronlidman @lxbarth

**Comment by aaronlidman** [comment]
Yes these are the first ones we want to detect on our own for this very reason. We have some queries to do this but the hurdle is keeping the data up to date. We're looking at a few ways of doing this but nothing tangible right now.

**Comment by planemad** [comment]
Good news is that all the high priority errors seem fixed now. Atleast those involving motorway/trunk/primary in the US.

**Comment by lxbarth** [comment]
@planemad this is awesome.
