### ISSUE TITLE
 Reduce Bbox on download data in JOSM

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#90]
@aaronlidman , could be possible to reduce Bbox on download for short ways, Sometime when I download places for fixing and for fix small roads, to-fix download a big parts and it take much time, example:
short way in to-fix:

![screenshot from 2015-03-25 10 33 11](https://cloud.githubusercontent.com/assets/1152236/6828286/dc356c84-d2da-11e4-96c7-0c6e86871f29.png)

Download in JOSM

![screenshot from 2015-03-25 10 33 55](https://cloud.githubusercontent.com/assets/1152236/6828313/0a9ed8a8-d2db-11e4-8640-2ae76325ad7c.png)

Would be good just download a small places for that roads.

**Comment by aaronlidman** [comment]
@Rub21 I made the download buffer half of the size of before. Can you try and let me know if that works? Feel free to close the ticket if it is good.
