### ISSUE TITLE
Select id of node or way on download data in JOSM

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#91]
@aaronlidman : Would be good select the id of node or way when we download in JOSM.(after click on edit in To-fix)
i think that is possible just adding the id on url download. When node or way is no selected is difficult to find the errors to missing to fix
Example: select the node that missing to be fix.
![screenshot from 2015-03-25 10 51 08](https://cloud.githubusercontent.com/assets/1152236/6828658/f00c42da-d2dc-11e4-9073-e922bb7f8c63.png)

**Comment by aaronlidman** [comment]
Yes I know. We need to figure out how to do this again. It got complicated. It will be back soon.

**Comment by planemad** [comment]
@aaronlidman this is a pretty important feature as there is a significant time loss in trying to identify the problem node.

We're continuing to use http://geohacker.in/unconnected-tiger/ to spot and fix all the high priority errors for now.

**Comment by tristen** [comment]
@aaronlidman did this break after my refactor? The query string that's passed to josm is located here: https://github.com/osmlab/to-fix/blob/074a773b8fd163e91c9d8ecc9db9896dc2daca96/src/components/task.js#L121-L125

**Comment by aaronlidman** [comment]
@tristen Yes, it's an optional thing that not all tasks would have. I just need to think about how to do it cleverly for a bit.

**Comment by tristen** [comment]
I'm also happy to discuss this with you. We keep special notes about each task here: https://github.com/osmlab/to-fix/blob/gh-pages/src/data/tasks.json we could add an entry to check and do special behaviour here.

**Comment by aaronlidman** [comment]
Yeah, @tristen this was previously the responsibility of the individual loaders, which we need to bring back in some way. We should get a quick fix out for this now, but loaders abstracted into their own modules need to come back in someway eventually.
